server:
  port: 8088
  servlet:
    context-path: /
spring:
  application:
    name: tim-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tim?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: ming122793.mm
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: KevinHikariPool
      maximum-pool-size: 15
      minimum-idle: 5
      auto-commit: true
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
